print ("Hello World")
print ("Hello there, General Kenobi")
print ("3rd sentence here")
print ("4th sentence")

print ("awoiejfioawef")
print ("awoiejfioawef")
print ("awoiejfioawef")
print ("awoiejfioawef")
print ("awoiejfioawef")
print ("awoiejfioawef")