print ("Hello World")
print ("Hello there, General Kenobi")
print ("3rd sentence here")
print ("4th sentence")

print ("uhhhh")
print ("ehhhhh")
print ("awoiejfioawef")
print ("awoiejfioawef")
print ("awoiejfioawef")
print ("awoiejfioawef")
